name: Build Widget App Launcher                                                
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Generate Gradle Wrapper Automatically
      run: gradle wrapper --gradle-version 9.3.1

    - name: Beri Izin Akses Gradle
      run: chmod +x gradlew

    - name: Proses Build APK
      run: ./gradlew assembleDebug --no-configuration-cache                       
    - name: Simpan Hasil APK
      uses: actions/upload-artifact@v4
      with:
        name: aplikasi-widget-app
        path: app/build/outputs/apk/debug/app-debug.apk

